# Generated by Django 2.2.3 on 2021-11-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jingqu'),
    ]

    operations = [
        migrations.AddField(
            model_name='jingqu',
            name='img',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='jingqu',
            name='city_url',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='jingqu',
            name='jingqu_url',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='jingqu',
            name='sheng_url',
            field=models.CharField(max_length=128),
        ),
    ]
