# Generated by Django 2.2.3 on 2021-11-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jingdian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='hid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JingQu'),
        ),
        migrations.AlterField(
            model_name='see',
            name='hid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JingQu'),
        ),
        migrations.AlterField(
            model_name='see',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
