# Generated by Django 2.2.3 on 2021-11-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211106_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='hid',
            new_name='jingqu',
        ),
        migrations.RenameField(
            model_name='see',
            old_name='hid',
            new_name='jingqu',
        ),
    ]
