# Generated by Django 2.2.3 on 2021-11-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211106_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
