# Generated by Django 2.2.13 on 2022-01-15 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=128, verbose_name='手机'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('content', models.CharField(max_length=256, verbose_name='内容')),
                ('score', models.IntegerField(verbose_name='评分')),
                ('jingdian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JingDian', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户名')),
            ],
        ),
    ]
